services:
  database:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partyup
    restart: unless-stopped
    networks:
      - partyup-app
  backend:
    depends_on:
      - database
      - ml
    restart: on-failure
    build: ./Back-end/Party-Up
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/partyup?max_allowed_packet=100MB&createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      ML_URL: http://ml:5000
    links:
      - database
      - ml
    networks:
      - partyup-app
  ml:
    depends_on:
      - database
    build: ./ML-Model/ML-Model-API
    ports:
      - 5000:5000
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: database
      DB_DATABASE: partyup
      DB_URL: jdbc:mysql://database:3306/partyup
    links:
      - database
    networks:
      - partyup-app
  frontend:
    depends_on:
      - backend
    links:
      - backend
    build: ./Front-end
    volumes:
      - './Front-end:/usr/src/app'
    ports:
      - 4200:4200
    networks:
      - partyup-app
volumes:
  db_data: {}

networks:
  partyup-app:
    